apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
    spec:
      containers:
      - name: metube
        image: ghcr.io/alexta69/metube:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /downloads
          name: metube-volume
      volumes:
      - name: metube-volume
        hostPath:
          path: /path/to/downloads
          type: DirectoryOrCreate